# ---- Application secrets (AWS Secrets Manager) ----
# Terraform creates the containers only. Issued credentials (JWT signing keys, Stripe, OpenAI,
# Cohere, SSO client secrets, the Bull Board secret, the app DB password) are put in with
# scripts/deploy/put-app-secrets.sh, so their values never pass through tfvars or state, and a
# rotation is not undone by the next apply. ECS injects one JSON key per variable:
#   valueFrom = "<secret arn>:KEY::"

# Credentials issued outside AWS (and the Bull Board secret)
resource "aws_secretsmanager_secret" "app" {
  name                    = "${var.project_name}/${var.environment}/app"
  description             = "Issued credentials for ${var.project_name} ${var.environment}: JWT signing keys, Stripe, OpenAI, Cohere, SSO client secrets, Bull Board. Values set out of band (scripts/deploy/put-app-secrets.sh)."
  recovery_window_in_days = var.recovery_window_days

  tags = {
    Name = "${var.project_name}-${var.environment}-app-secrets"
  }
}

# The application database login's password, apart from the rest so the deploy pipeline (which
# creates and migrates the role) can read it without reading the signing keys
resource "aws_secretsmanager_secret" "db_app" {
  name                    = "${var.project_name}/${var.environment}/db-app"
  description             = "DB_APP_PASSWORD for ${var.project_name} ${var.environment}. Value set out of band (scripts/deploy/put-app-secrets.sh)."
  recovery_window_in_days = var.recovery_window_days

  tags = {
    Name = "${var.project_name}-${var.environment}-db-app-secret"
  }
}

# The Redis AUTH token is generated by Terraform (modules/elasticache), so it is in state already;
# Terraform also writes it here for the tasks
resource "aws_secretsmanager_secret" "redis" {
  name                    = "${var.project_name}/${var.environment}/redis"
  description             = "REDIS_PASSWORD (ElastiCache AUTH token) for ${var.project_name} ${var.environment}. Managed by Terraform."
  recovery_window_in_days = var.recovery_window_days

  tags = {
    Name = "${var.project_name}-${var.environment}-redis-secret"
  }
}

resource "aws_secretsmanager_secret_version" "redis" {
  secret_id     = aws_secretsmanager_secret.redis.id
  secret_string = jsonencode({ REDIS_PASSWORD = var.redis_password })
}

# ---- IAM policy for the ECS task execution role ----
# ECS reads the secrets at container start; the containers themselves only get the keys their
# task definition names.
resource "aws_iam_policy" "ecs_read_secrets" {
  name        = "${var.project_name}-${var.environment}-ecs-read-secrets"
  description = "Allows the ECS task execution role to read the application secrets"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["secretsmanager:GetSecretValue"]
        Resource = [
          aws_secretsmanager_secret.app.arn,
          aws_secretsmanager_secret.db_app.arn,
          aws_secretsmanager_secret.redis.arn,
        ]
      }
    ]
  })

  tags = {
    Name = "${var.project_name}-${var.environment}-ecs-secrets-policy"
  }
}
