variable "project_name" {
  description = "Project name used for resource naming"
  type        = string
}

variable "environment" {
  description = "Environment name (staging, production)"
  type        = string
}

variable "redis_password" {
  description = "ElastiCache AUTH token (generated by the elasticache module); empty when TLS/AUTH is off"
  type        = string
  sensitive   = true
  default     = ""
}

variable "recovery_window_days" {
  description = "Days a deleted secret can be restored (0 deletes at once; 7–30 otherwise)"
  type        = number
  default     = 7
}
