#!/usr/bin/env node

/**
 * One-time generator: exports pre-computed ruleset_chunks (with embeddings)
 * from the running database into a SQL seed file.
 *
 * Usage:
 *   pnpm db:generate-chunk-seed
 *   # or: npx ts-node scripts/generate-chunk-seed.ts
 *
 * Requires: database running with chunks already ingested (run ingestion for
 *           the 5 demo rulesets first via POST /rulesets/:key/ingest).
 * Output:   scripts/seeds/010_seed_ruleset_chunks.sql
 */

import { Pool } from 'pg';
import * as fs from 'fs';
import * as path from 'path';

const DEMO_RULESET_IDS = [
  '20000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000002',
  '20000000-0000-0000-0000-000000000003',
  '20000000-0000-0000-0000-000000000004',
  '20000000-0000-0000-0000-000000000005',
];

interface ChunkRow {
  id: string;
  ruleset_id: string;
  ruleset_version_id: string;
  chunk_index: number;
  content: string | null;
  embedding: string | null;
  metadata: string;
  created_at: Date | string;
}

async function main(): Promise<void> {
  // Load env from apps/api/.env (same as seed runner)
  const dotenv = await import('dotenv').then((m) => m.default);
  dotenv.config({
    path: path.resolve(__dirname, '../apps/api/.env'),
  });

  const pool = new Pool({
    host: process.env.DB_HOST || 'localhost',
    port: Number(process.env.DB_PORT) || 5432,
    database: process.env.DB_NAME || 'complytude',
    user: process.env.DB_USER || 'postgres',
    password: process.env.DB_PASSWORD || 'postgres',
  });

  const ids = DEMO_RULESET_IDS.map((id) => `'${id}'`).join(', ');

  const { rows } = await pool.query<ChunkRow>(`
    SELECT
      id,
      ruleset_id,
      ruleset_version_id,
      chunk_index,
      content,
      embedding::text AS embedding,
      metadata::text AS metadata,
      created_at
    FROM public.ruleset_chunks
    WHERE ruleset_id IN (${ids})
    ORDER BY ruleset_id, chunk_index
  `);

  if (rows.length === 0) {
    console.error(
      'No chunks found. Did you run ingestion for the demo rulesets?',
    );
    process.exit(1);
  }

  const lines = [
    '-- =========================',
    '-- Seed Script 010: Pre-computed Ruleset Chunk Embeddings',
    '-- =========================',
    '-- Auto-generated by: pnpm db:generate-chunk-seed',
    `-- Generated at: ${new Date().toISOString()}`,
    `-- Chunks: ${rows.length}`,
    '-- Idempotent: Deletes existing demo chunks then re-inserts',
    '-- Dependencies: Requires rulesets (009) to be seeded first',
    '-- =========================',
    '',
    'BEGIN;',
    '',
    '-- Remove any existing chunks for the 5 demo rulesets',
    `DELETE FROM public.ruleset_chunks WHERE ruleset_id IN (${ids});`,
    '',
  ];

  let prevRuleset: string | null = null;

  for (const row of rows) {
    if (row.ruleset_id !== prevRuleset) {
      const meta = JSON.parse(row.metadata) as { rulesetKey: string };
      lines.push(`-- ── ${meta.rulesetKey} ──`);
      prevRuleset = row.ruleset_id;
    }

    const content = (row.content || '').replace(/'/g, "''");
    const metadata = (row.metadata || '').replace(/'/g, "''");
    const embedding = (row.embedding || '').replace(/'/g, "''");
    const ts =
      row.created_at instanceof Date
        ? row.created_at.toISOString()
        : String(row.created_at);

    lines.push(
      `INSERT INTO public.ruleset_chunks (id, ruleset_id, ruleset_version_id, chunk_index, content, embedding, metadata, created_at) VALUES ('${row.id}', '${row.ruleset_id}', '${row.ruleset_version_id}', ${row.chunk_index}, '${content}', '${embedding}', '${metadata}'::jsonb, '${ts}'::timestamptz);`,
    );
  }

  lines.push('', 'COMMIT;', '');
  lines.push('-- =========================');
  lines.push('-- Verification');
  lines.push('-- =========================');
  lines.push('');
  lines.push('DO $$');
  lines.push('DECLARE');
  lines.push('    chunk_count INT;');
  lines.push('BEGIN');
  lines.push(
    `    SELECT COUNT(*) INTO chunk_count FROM public.ruleset_chunks WHERE ruleset_id IN (${ids});`,
  );
  lines.push("    RAISE NOTICE 'Ruleset chunks seeded: %', chunk_count;");
  lines.push('END $$;');

  const outPath = path.resolve(__dirname, 'seeds/010_seed_ruleset_chunks.sql');
  fs.writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');

  const sizeKB = (fs.statSync(outPath).size / 1024).toFixed(1);
  console.log(`✅ Generated ${outPath}`);
  console.log(`   ${rows.length} chunks, ${sizeKB} KB`);

  await pool.end();
}

main().catch((err) => {
  console.error('Failed:', (err as Error).message);
  process.exit(1);
});
